version: "3"
services:
  backend:
    depends_on:
      - mongodb
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb://mongodb:27017/kenility
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:
  node_modules: 